# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c3e8adc1256f9efbb913165b6eb485f62190c204dd924bdcaaf4c6acf91c1710a4c03b962ac8d22b08a45797680fdd8d443984091bb5ae8ab9550ab08ea1764

test:
  secret_key_base: fd3aebbf34713cdd17831302cfc9d717eb4e981a7dbb05a8ad5c789d93a35bc846fd70a4965505243e4bc63aa76575b9baeac734410904fe2a7239a348beed05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
